# excel-vba.toml
# Configuration file for the excel-vba CLI tool
# Place this file in your working directory or specify its path with --conf

[general]
# Path and filname of the Office document to work with.
# The path can be relative to this TOML config file, which means it can also be left out,
# so that 'file' will get searched for in the directory of this config file
file = "test_doc.xlsm"

# Target directory for exporting/importing VBA modules and PowerQuery M code
# either absolute path or relative to parent path of 'file' setting
#
# Some placeholders can be used here:
# {general.file.name} will be replaced with the pure filename of the 'file' setting, without path and file extension
# {general.file.fullname} will be replaced with the filename of the 'file' setting, including the file extension
# {general.file.path} will be replaced with the parent path of the 'file' setting, after it has been resolved
# {general.file.vbaproject} will be replaced with the VBA project name found within the office file
vba-directory = "./src/vba"
pq-directory = "./pq-M"

# Encoding for reading/writing VBA files (e.g., "utf-8", "windows-1252")
# valid codecs: see https://docs.python.org/3/library/codecs.html#standard-encodings
# common for legacy VBA files on Windows is "windows-1252"
encoding = "windows-1252"

# Automatically detect encoding if true
detect-encoding = false

# Save module headers (attributes) in separate files
in-file-headers = true
save-headers = false

# Enable verbose logging
verbose = true

# Log output to a file (specify path or leave empty for no logfile)
logfile = "./excel-vba.log"

# Use RubberduckVBA folder annotations for module organization
rubberduck-folders = true

# Run Office application in invisible mode (background, no window)
invisible-mode = false

# Execution mode: "export", "import", "edit"
# mode = "edit"
open-folder = false # Open the export directory in file explorer after export, valid for export mode only

[office]
# Office application to use ("excel", "word", "access")
application = "excel"

# Additional options for Office automation
timeout-seconds = 60

[excel]
# Option to use xlwings for Excel operations (if installed)
use-xlwings = false
